Hospital/Controllers/BedController.cs
using Hospital.Models;
using System.Web.Configuration;
using System.Web.Mvc;
using Hospital.Interfaces;
using System.Collections.Generic;

namespace Hospital.Controllers
{
     [Authorize]
    public class BedController : Controller
    {
        public BedController()
            : this(new Repository(WebConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString))
        {

        }

        public BedController(IBedRepository Beds)
        {
            BedRepository = Beds;
        }

        public IBedRepository BedRepository { get; private set; }
        
        [HttpGet]
        public ActionResult BedList()
        {
            List<IBed> Beds;
            if (ModelState.IsValid)
                Beds = BedRepository.GetBeds();
            else
                Beds = new List<IBed>();

            return View(Beds);
        }

    }

}

Hospital/Controllers/DoctorController.cs
using Hospital.Models;
using System.Web.Configuration;
using System.Web.Mvc;
using Hospital.Interfaces;
using System.Collections.Generic;
using System.Linq;

namespace Hospital.Controllers
{
    [Authorize]
    public class DoctorController : Controller
    {
        public DoctorController()
            : this(new Repository(WebConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString))
        {
        }

        public DoctorController(Repository Repo)
        {
            Repository = Repo;
        }

        public Repository Repository { get; private set; }

        [HttpGet]
        public ActionResult DoctorList(string name)
        {
            List<IDoctor> Doctors = null;
            if (ModelState.IsValid)
            {
                if (!string.IsNullOrEmpty(name))
                    Doctors = Repository.GetDoctors().Where(e => e.Name.ToUpper().Contains(name.ToUpper())).ToList<IDoctor>();
                else
                    Doctors = Repository.GetDoctors();
            }
            else
                Doctors = new List<IDoctor>();
         
            return View(Doctors);
        }

        [HttpGet]
        public ActionResult AssignDoctor(int DoctorID)
        {
            ViewModelDoctorAssign DoctorPatientInfo = new ViewModelDoctorAssign();
            DoctorPatientInfo.Doctor = (Doctor) Repository.GetDoctor(DoctorID);
            DoctorPatientInfo.Patients = (IEnumerable<IPatient>) Repository.GetPatients();
            DoctorPatientInfo.Beds = (IEnumerable<IBed>) Repository.GetBeds();
            DoctorPatientInfo.Visit = new Visit();
            return View(DoctorPatientInfo);
        }


        [HttpPost]
        public ActionResult AssignDoctor(Doctor Doctor, int Patients, int Beds, Visit Visit)
        {

            if(ModelState.IsValid)
            {
                bool success = Repository.RegisterVisit(Doctor.Id, Patients, Beds, Visit.DateOfVisit, Visit.Symptoms, Visit.Disease, Visit.Treatment, Visit.isInPatient);
                 
                if (success)
                    return RedirectToAction("DoctorList");
            }
            return AssignDoctor(Doctor.Id);
          
        }

        [HttpGet]
        public ActionResult HistoryDoctor(int DoctorID)
        {
            IList<IVisit> Visits;
            IDoctor Doc;
            if (ModelState.IsValid)
            {
                Visits = Repository.GetDoctorVisits(DoctorID);
                Doc = Repository.GetDoctor(DoctorID);

            }
            else
            {
                Visits = new List<IVisit>();
                Doc = new Doctor();
            }

            ViewModelDoctorVisits vm = new ViewModelDoctorVisits();
            vm.Doctor = Doc;
            vm.Visits = Visits;

            return View(vm);
        }

    }
       
}

Hospital/Controllers/PatientController.cs
using System.Web.Mvc;
using Hospital.Interfaces;
using Hospital.Models;
using System.Web.Configuration;
using System.Collections.Generic;
using System.Linq;
using System;

namespace Hospital.Controllers
{
    [Authorize]
    public class PatientController : Controller
    {
        private ViewModel _vm;

        public ViewModel ViewModel { get; private set; }

        public PatientController()
            : this(new Repository(WebConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString))
        {
            _vm = new ViewModel();
            _vm.Search = new VisitSearch();
            _vm.Search.DateOfVisit = DateTime.Today;
        }

        public PatientController(Repository Repository)
        {
            this.Repository = Repository;
        }


        public Repository Repository {get; private set;}

        [HttpGet]
        public ActionResult PatientList(string Name)
        {
            List<IPatient> Patients = null;

            if (ModelState.IsValid)
            {
                if (!string.IsNullOrEmpty(Name))
                    Patients = Repository.GetPatients().Where(e => e.Name.ToUpper().Contains(Name.ToUpper())).ToList<IPatient>();
                else
                    Patients = Repository.GetPatients();

            }
            else
                Patients = new List<IPatient>();
            
            return View(Patients);
        }



        [HttpGet]
        public ActionResult PatientVisits()
        {
            if(ModelState.IsValid)
                 _vm.PatientVisitations = Repository.GetVisits();
            else 
                _vm.PatientVisitations = new List<IVisit>();

            return View(_vm);
        }

        [HttpPost]
        public ActionResult PatientVisits(ViewModel vm)
        {
            if (ModelState.IsValid)
            {
                IEnumerable<IVisit> Visits = Repository.GetVisits();

                if (!String.IsNullOrEmpty(vm.Search.Name))
                    Visits = Visits.Where(a => a.Name.ToUpper().Contains(vm.Search.Name.ToUpper()));

                if(vm.Search.DateOfVisit != null)
                    Visits = Visits.Where(a => a.DateOfVisit >= vm.Search.DateOfVisit);

                if (vm.Search.DateOfDischarge != null)
                    Visits = Visits.Where(a => a.DateOfDischarge <= vm.Search.DateOfDischarge);

                _vm.PatientVisitations = Visits.ToList<IVisit>();
                
            }
            else
                _vm.PatientVisitations = new List<IVisit>();

            return View(_vm);
        }


        [HttpGet]
        public ActionResult PatientEditList()
        {
            _vm.Patients = Repository.GetPatients();
            return View(_vm);
        }

        [HttpGet]
        public ActionResult PatientEdit(int PatientID)
        {
            IPatient Patient = Repository.GetPatient(PatientID);
            return View(Patient);
        }

        [HttpPost]
        public ActionResult PatientEdit(Patient Patient)
        {
            bool success = Repository.UpdatePatient(Patient);
            if(success)
                return RedirectToAction("PatientEditList");

            return View(Patient);
        }

        [HttpGet]
        public ActionResult PatientNew()
        {
            return View();
        }

        [HttpPost]
        public ActionResult PatientNew(Patient Patient)
        {
            bool success = Repository.RegisterPatient(Patient);
            if (success)
                return RedirectToAction("PatientEditList");

            return View(Patient);
        }

        [HttpGet]
        public ActionResult PatientDischarge(int VisitId)
        {
           
            IVisit Visit = Repository.GetVisit(VisitId);
            IBed Bed = Repository.GetBed(Visit.BedID);
            ViewModelDischargeInvoice Model = new ViewModelDischargeInvoice();
            Model.Bed = Bed;
            Model.Visit = Visit;

            return View(Model);
        }
        [HttpPost]
        public string PatientDischarge(string cc, int vid)
        {
            bool success = Repository.DischargePatient(vid);
            if (success)
                return "OK";
            else
                return "Error";
        }
    }
}

Hospital/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Hospital Manager Enterprise</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("ScriptTag", false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index", "Home")"><span><i class="fa fa-hospital-o"></i> Hospital Manager Enterprise</span></a>
            </div>

            <div class="navbar-collapse collapse">
@if (Request.IsAuthenticated)
{ 
                <ul class="nav navbar-nav">
                    <li><a href="@Url.Action("PatientList", "Patient")"><span><i class="fa fa-wheelchair"></i> Patients</span></a></li>
                    <li><a href="@Url.Action("PatientEditList", "Patient")"><span><i class="fa fa-edit"></i> Registration</span></a></li>
                    <li><a href="@Url.Action("PatientVisits", "Patient")"><span><i class="fa fa-users"></i> Visits</span></a></li>
                    <li><a href="@Url.Action("DoctorList", "Doctor")"><span><i class="fa fa-user-md"> Doctors</i></span></a></li>
                    <li><a href="@Url.Action("BedList", "Bed")"><span><i class="fa fa-user"></i> Beds</span></a></li>
                    <li><a href="@Url.Action("SiteMap", "Home")"><span><i class="fa fa-sitemap"></i> SiteMap</span></a></li>
                </ul>
}  
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div class="container-inner">
            @RenderBody()
        </div>
        <hr />
        <footer>
            <p class="text-muted">&copy; @DateTime.Now.Year - Hospital Manager Enterprise v1.0</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>